### ISSUE TITLE
NETCore Compatability

### ISSUE THREAD

**Issue by Jimmy062006** [Spksh/TentacleSoftware.TeamSpeakQuery#15]
Why are these not NETCore compatible ?

They kinda are. I've recompiled them as (what so far seems) fully compatible are you interested in a PR for it or are these supposed to be .NET 4.6.1 only ?

**Comment by Spksh** [comment]
Because I wrote all this 4 years ago and haven't used it since 😄.  

You're talking about changing the project to .NET Standard 2.0, yeah? e.g. https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/

Interested in a PR for this, yes.

**Comment by Jimmy062006** [comment]
OK Let me actually fork it rather then gitclone.

**Comment by Spksh** [comment]
Ref pull #16 . Will take a look after work today, thanks.

**Comment by Spksh** [comment]
Accepted pull #16, checked in a few fixes; I missed that you'd targeted `netcoreapp2.0` instead of `dotnetstandard2.0`, and I bumped the version to 2.x.x because this will break usage in .NET 4.5.x.

End result: https://www.nuget.org/packages/TentacleSoftware.TeamSpeakQuery/2.0.0-rc3

Looks good in my tests. I have a few things I wanted to do for #17 before I remove the RC tag, but the latest pre-release nuget package now works with .NET Core 2.0+, .NET 4.6.1+, and Mono 5.4+.

Thanks for the help.
